---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        type: db
    spec:
      volumes:                        # indicates which PVC are available for this Deployment
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:              # indicates which Volume (from spec.template.spec.volumes) should be used
            - name: postgres-storage   # name of the Volume
              mountPath: /var/lib/postgresql/data   # path inside the container
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:               # indicates into which pods ClusterIP provides access
    app: postgres
  ports:
    - port: 5432          # port exposed outside ClusterIP
      targetPort: 5432    # port exposed by Pod
---


# --
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
#   namespace: default
#   labels:
#     app: postgres
# data:
#   POSTGRES_DB: postgresdb
#   POSTGRES_USER: admin
#   POSTGRES_PASSWORD: test123

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres
#   namespace: default
#   labels:
#     app: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: "postgres:9.6-alpine"
#         env:
#         - name: POSTGRES_DB
#           valueFrom:
#             configMapKeyRef:
#               key: POSTGRES_DB
#               name: postgres-config
#         - name: POSTGRES_USER
#           valueFrom:
#             configMapKeyRef:
#               key: POSTGRES_USER
#               name: postgres-config
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             configMapKeyRef:
#               key: POSTGRES_PASSWORD
#               name: postgres-config
#         ports:
#           - containerPort: 5432
#             name: postgres
#         volumeMounts:
#           - name: postgres-storage
#             mountPath: /var/lib/postgresql/data
#       volumes:
#         - name: postgres-storage
#           persistentVolumeClaim:
#             claimName: postgres-pv-claim

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres
# spec:
#   ports:
#     - port: 5432
#   selector:
#     app: postgres
#   type: NodePort


